### ISSUE TITLE
Path Prefix

### ISSUE THREAD

**Issue by janis91** [stevenleeg/twproxy#1]
Hi, today I tried twproxy and I am very satisfied with this simple solution in order to make TW5 a little bit better from the authentication point of view.

Unfortunately I found a strange behavior when I try to use a Path prefix with my tw5 nodejs client/server edition.
 [Path Prefix](http://tiddlywiki.com/#Using%20a%20custom%20path%20prefix%20with%20the%20client-server%20edition)

For me it is necessary that tw5 serves under a sub-directory or sub-path like "http://my-domain/tiddlywiki", because I want to have multiple applications available under one domain in my nginx (with ssl encryption). A subdomain is no solution in my case, because I am not allowed to add subdomains from my provider.

TW5 specifies the path prefix as an optional command line parameter for the server command:
[Server Command](http://tiddlywiki.com/#ServerCommand)

If I configure a path prefix in tw5 and want to use twproxy I get some error messages and tw5 is not working:

> Sync error while processing '$:/StoryList': XMLHttpRequest error code: 500

> Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: json is null

If I browse the original URL without twproxy, everything is fine, so I guess it's the path prefix issue, that might be the problem.

In my opinion you could improve twproxy, by adding this feature.

**Comment by stevenleeg** [comment]
Ahh yep, I think I know what's happening here. I'll get this patched up and release a new version as soon as I get time (probably in the next couple of days).

Thanks for the tip! I'll report in when this is fixed.

**Comment by janis91** [comment]
@stevenleeg : Did you make any progress with this topic? Because maybe I'll get some time this weekend and could check, if I can get a working solution (Unfortunately i am not very familiar with ruby).

**Comment by stevenleeg** [comment]
Hey Janis,

Unfortunately not, I’ve been pretty swamped this week with some other side projects. This is still on my radar though. If you do end up getting some free time feel free to try it out and submitting a PR. Don’t worry about your ruby; I can provide feedback and make sure it’s in good shape to ship!

**Comment by stevenleeg** [comment]
Fixed in PR #2.
